# SPDX-FileCopyrightText: 2025 Derek Sauer
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Cargo configuration appropriate for ESP32 chips.

[build]
target = "riscv32imc-unknown-none-elf"

[target.'cfg(all(any(target_arch = "riscv32", target_arch = "xtensa"), target_os = "none"))']
runner = "probe-rs run"

[env]
DEFMT_LOG = "debug"
ESP_WIFI_CONFIG_COUNTRY_CODE = "CA"
