# SPDX-FileCopyrightText: 2025 Derek Sauer
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Using an Espressif Systems ESP32C3-MINI-1
[target.'cfg(target_arch = "riscv32")']
runner = "probe-rs run --chip esp32c3 --protocol jtag"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "force-frame-pointers"
  ]

[build]
target = "riscv32imc-unknown-none-elf"

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort"]

